# -*- coding: utf8 -*-

# Copyright 2017-2022 NLCI (http://www.nlci.in/fonts/)
# Apache License v2.0

class Charset:
    common_name = 'NLCI: Tamil script'
    native_name = 'Tamil script'
    abbreviation = 'Taml'
    key = 0x0B95
    glyphs = [
        0x0323,  # COMBINING DOT BELOW
        0x0B82,  # TAMIL SIGN ANUSVARA
        0x0B83,  # TAMIL SIGN VISARGA
        0x0B85,  # TAMIL LETTER A
        0x0B86,  # TAMIL LETTER AA
        0x0B87,  # TAMIL LETTER I
        0x0B88,  # TAMIL LETTER II
        0x0B89,  # TAMIL LETTER U
        0x0B8A,  # TAMIL LETTER UU
        0x0B8E,  # TAMIL LETTER E
        0x0B8F,  # TAMIL LETTER EE
        0x0B90,  # TAMIL LETTER AI
        0x0B92,  # TAMIL LETTER O
        0x0B93,  # TAMIL LETTER OO
        0x0B94,  # TAMIL LETTER AU
        0x0B95,  # TAMIL LETTER KA
        0x0B99,  # TAMIL LETTER NGA
        0x0B9A,  # TAMIL LETTER CA
        0x0B9C,  # TAMIL LETTER JA
        0x0B9E,  # TAMIL LETTER NYA
        0x0B9F,  # TAMIL LETTER TTA
        0x0BA3,  # TAMIL LETTER NNA
        0x0BA4,  # TAMIL LETTER TA
        0x0BA8,  # TAMIL LETTER NA
        0x0BA9,  # TAMIL LETTER NNNA
        0x0BAA,  # TAMIL LETTER PA
        0x0BAE,  # TAMIL LETTER MA
        0x0BAF,  # TAMIL LETTER YA
        0x0BB0,  # TAMIL LETTER RA
        0x0BB1,  # TAMIL LETTER RRA
        0x0BB2,  # TAMIL LETTER LA
        0x0BB3,  # TAMIL LETTER LLA
        0x0BB4,  # TAMIL LETTER LLLA
        0x0BB5,  # TAMIL LETTER VA
        0x0BB6,  # TAMIL LETTER SHA
        0x0BB7,  # TAMIL LETTER SSA
        0x0BB8,  # TAMIL LETTER SA
        0x0BB9,  # TAMIL LETTER HA
        0x0BBE,  # TAMIL VOWEL SIGN AA
        0x0BBF,  # TAMIL VOWEL SIGN I
        0x0BC0,  # TAMIL VOWEL SIGN II
        0x0BC1,  # TAMIL VOWEL SIGN U
        0x0BC2,  # TAMIL VOWEL SIGN UU
        0x0BC6,  # TAMIL VOWEL SIGN E
        0x0BC7,  # TAMIL VOWEL SIGN EE
        0x0BC8,  # TAMIL VOWEL SIGN AI
        0x0BCA,  # TAMIL VOWEL SIGN O
        0x0BCB,  # TAMIL VOWEL SIGN OO
        0x0BCC,  # TAMIL VOWEL SIGN AU
        0x0BCD,  # TAMIL SIGN VIRAMA
        0x0BD0,  # TAMIL OM
        0x0BD7,  # TAMIL AU LENGTH MARK
        0x0BE6,  # TAMIL DIGIT ZERO
        0x0BE7,  # TAMIL DIGIT ONE
        0x0BE8,  # TAMIL DIGIT TWO
        0x0BE9,  # TAMIL DIGIT THREE
        0x0BEA,  # TAMIL DIGIT FOUR
        0x0BEB,  # TAMIL DIGIT FIVE
        0x0BEC,  # TAMIL DIGIT SIX
        0x0BED,  # TAMIL DIGIT SEVEN
        0x0BEE,  # TAMIL DIGIT EIGHT
        0x0BEF,  # TAMIL DIGIT NINE
        0x0BF0,  # TAMIL NUMBER TEN
        0x0BF1,  # TAMIL NUMBER ONE HUNDRED
        0x0BF2,  # TAMIL NUMBER ONE THOUSAND
        0x0BF3,  # TAMIL DAY SIGN
        0x0BF4,  # TAMIL MONTH SIGN
        0x0BF5,  # TAMIL YEAR SIGN
        0x0BF6,  # TAMIL DEBIT SIGN
        0x0BF7,  # TAMIL CREDIT SIGN
        0x0BF8,  # TAMIL AS ABOVE SIGN
        0x0BF9,  # TAMIL RUPEE SIGN
        0x0BFA,  # TAMIL NUMBER SIGN
        0x1CDA,  # VEDIC TONE DOUBLE SVARITA
        0xA8F3,  # DEVANAGARI SIGN CANDRABINDU VIRAMA
        0x11301,  # GRANTHA SIGN CANDRABINDU
        0x11303,  # GRANTHA SIGN VISARGA
        0x1133B,  # COMBINING BINDU BELOW
        0x1133C,  # GRANTHA SIGN NUKTA
        0x11FC0,  # TAMIL FRACTION ONE THREE-HUNDRED-AND-TWENTIETH
        0x11FC1,  # TAMIL FRACTION ONE ONE-HUNDRED-AND-SIXTIETH
        0x11FC2,  # TAMIL FRACTION ONE EIGHTIETH
        0x11FC3,  # TAMIL FRACTION ONE SIXTY-FOURTH
        0x11FC4,  # TAMIL FRACTION ONE FORTIETH
        0x11FC5,  # TAMIL FRACTION ONE THIRTY-SECOND
        0x11FC6,  # TAMIL FRACTION THREE EIGHTIETHS
        0x11FC7,  # TAMIL FRACTION THREE SIXTY-FOURTHS
        0x11FC8,  # TAMIL FRACTION ONE TWENTIETH
        0x11FC9,  # TAMIL FRACTION ONE SIXTEENTH-1
        0x11FCA,  # TAMIL FRACTION ONE SIXTEENTH-2
        0x11FCB,  # TAMIL FRACTION ONE TENTH
        0x11FCC,  # TAMIL FRACTION ONE EIGHTH
        0x11FCD,  # TAMIL FRACTION THREE TWENTIETHS
        0x11FCE,  # TAMIL FRACTION THREE SIXTEENTHS
        0x11FCF,  # TAMIL FRACTION ONE FIFTH
        0x11FD0,  # TAMIL FRACTION ONE QUARTER
        0x11FD1,  # TAMIL FRACTION ONE HALF-1
        0x11FD2,  # TAMIL FRACTION ONE HALF-2
        0x11FD3,  # TAMIL FRACTION THREE QUARTERS
        0x11FD4,  # TAMIL FRACTION DOWNSCALING FACTOR KIIZH
        0x11FD5,  # TAMIL SIGN NEL
        0x11FD6,  # TAMIL SIGN CEVITU
        0x11FD7,  # TAMIL SIGN AAZHAAKKU
        0x11FD8,  # TAMIL SIGN UZHAKKU
        0x11FD9,  # TAMIL SIGN MUUVUZHAKKU
        0x11FDA,  # TAMIL SIGN KURUNI
        0x11FDB,  # TAMIL SIGN PATHAKKU
        0x11FDC,  # TAMIL SIGN MUKKURUNI
        0x11FDD,  # TAMIL SIGN KAACU
        0x11FDE,  # TAMIL SIGN PANAM
        0x11FDF,  # TAMIL SIGN PON
        0x11FE0,  # TAMIL SIGN VARAAKAN
        0x11FE1,  # TAMIL SIGN PAARAM
        0x11FE2,  # TAMIL SIGN KUZHI
        0x11FE3,  # TAMIL SIGN VELI
        0x11FE4,  # TAMIL WET CULTIVATION SIGN
        0x11FE5,  # TAMIL DRY CULTIVATION SIGN
        0x11FE6,  # TAMIL LAND SIGN
        0x11FE7,  # TAMIL SALT PAN SIGN
        0x11FE8,  # TAMIL TRADITIONAL CREDIT SIGN
        0x11FE9,  # TAMIL TRADITIONAL NUMBER SIGN
        0x11FEA,  # TAMIL CURRENT SIGN
        0x11FEB,  # TAMIL AND ODD SIGN
        0x11FEC,  # TAMIL SPENT SIGN
        0x11FED,  # TAMIL TOTAL SIGN
        0x11FEE,  # TAMIL IN POSSESSION SIGN
        0x11FEF,  # TAMIL STARTING FROM SIGN
        0x11FF0,  # TAMIL SIGN MUTHALIYA
        0x11FF1,  # TAMIL SIGN VAKAIYARAA
        0x11FFF,  # TAMIL PUNCTUATION END OF TEXT
    ]
